### ISSUE TITLE
Y U NO ICMP

### ISSUE THREAD

**Issue by tbodt** [LEGOlord208/PingPlus#1]
ICMP IZ DANK

ICMP DOZNT RQUIER AN HTTP RQEST

ICMP IZ FAAAASTR

**Comment by tbodt** [comment]
`ping(1)` uses icmp

**Comment by LEGOlord208** [comment]
I will check it out, thanks!

**Comment by LEGOlord208** [comment]
ICMP is not supported in Java. If you want me to use lower level socket instead, please re-open this commit. Other than that, I will close this now.
